# Generated by Django 2.1 on 2020-12-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20201212_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='is_closed',
        ),
    ]
