# Generated by Django 3.1.4 on 2020-12-16 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20201216_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='category',
            field=models.ManyToManyField(blank=True, to='restaurants.Category'),
        ),
        migrations.AlterField(
            model_name='categorymatch',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.category'),
        ),
        migrations.AlterField(
            model_name='categorymatch',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.info'),
        ),
    ]
