# Generated by Django 3.1.4 on 2020-12-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_info_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='price',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='review_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='zip_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
