# Generated by Django 3.1.4 on 2020-12-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20201216_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryMatch',
        ),
    ]
