# Generated by Django 3.1.4 on 2020-12-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='date_posted',
        ),
    ]
